
knp_snappy:
    temporary_folder: "%kernel.cache_dir%/snappy"
    process_timeout: 20
    pdf:
        enabled:    true
        # If you have wkhtmltopdf as an environment variable you don't need to provide the
        # full path to the executable, use it in the same way as you use in the console
        #binary:  "wkhtmltopdf"
            #        binary:     '%env(WKHTMLTOPDF_PATH)%'

        binary:     "\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\""
        options:    []
    image:
        enabled:    true
#        binary:     '%env(WKHTMLTOIMAGE_PATH)%'

        binary:     "\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltoimage.exe\""
        options:    []
